### ISSUE TITLE
release 0.8.0 doesn't properly honor instance_type

### ISSUE THREAD

**Issue by mfischer-zd** [test-kitchen/kitchen-ec2#114]
If you specify `instance_type` but not `flavor_id` in the ec2 driver configuration, the default instance type of `m1.small` will be used, even if the `instance_type` is different.

This bug is in 0.8.0.

**Comment by tyler-ball** [comment]
Hey @mfischer-zd, thanks for the report.  This should be fixed in 0.9.0 - `flavor_id` has been deprecated in favor of `instance_type`.  If you don't provide either, it now defaults to `m1.small` but if you provide `flavor_id` it will issue a warning and then use that.  Let me know if this is not fixed!
