### ISSUE TITLE
Default AMIs for Windows not available

### ISSUE THREAD

**Issue by emiliogarcia** [test-kitchen/kitchen-ec2#174]
I can't find the default AMIs for Windows in us-east-1
https://github.com/test-kitchen/kitchen-ec2/blob/master/data/amis.json

I get:
No AMIs found matching your filter criteria
or not authorised to launch the AMI from the kitchen log.

Were those AMIs special? AFAIK WinRM is not enabled by default in the ones provided by Amazon. What does the Windows AMI needs to be able to work with Kitchen-ec2?

**Comment by zl4bv** [comment]
Amazon release new Windows AMIs around once per month. The AMIs are then available for about six weeks after which you can no longer start new instances with those AMIs (the expectation being that you start new instances with this month's AMIs). Based on your error, it is most likely that the AMIs listed in amis.json are out of date now - which makes sense given they were last updated on June 5.

By default kitchen-ec2 [provides](https://github.com/test-kitchen/kitchen-ec2/blob/master/lib/kitchen/driver/ec2.rb#L476-490) user-data that enables WinRM for Windows guests. 

You'll need to make sure the security group of the test kitchen instance allows WinRM traffic on TCP port 5985. Also, either you need to provide a username and password for test-kitchen to connect to the instance with, or an SSH key and key ID so that kitchen-ec2 can decrypt the EC2 generated Windows password (with the default username Administrator).

**Comment by tjnicholas** [comment]
It'd be easier to avoid stale AMI IDs if #177 was merged.

**Comment by cheeseplus** [comment]
#177 is merged so calling this closed.
