### ISSUE TITLE
Ability to use the instance metadata such as public dns, public ip, private ip, hostname etc as cookbook attributes

### ISSUE THREAD

**Issue by frezbo** [test-kitchen/kitchen-ec2#313]
I have searched a lot to try and use the instance data as attributes in my .kitchen.yml file with no success. Does this feature already exist?

**Comment by cheeseplus** [comment]
That feature doesn't exists because it can't. The kitchen.yml is largely a static file (technically you can ERB template inside of it). If you need to access ec2 specific metadata inside a chef run/recipe, it's already there by virtue of Ohai (the system discovery tool) via `node['ec2']`.

Closing this since it's not a feature but a question (now answered).
