### ISSUE TITLE
Unable to load provisioning/aws_driver when running recipe from instance

### ISSUE THREAD

**Issue by stevegreen22** [test-kitchen/kitchen-ec2#325]
I'm trying to set up kitchen and having difficulties with this aspect.

As far as I can tell, the yml looks correct but it's constantly error'ing when running the recipe.

The error:
 LoadError
 ---------
 cannot load such file -- chef/provisioning/aws_driver
and
       [2017-07-04T15:09:11+00:00] ERROR: cannot load such file -- chef/provisioning/aws_driver
       [2017-07-04T15:09:11+00:00] ERROR: cannot load such file -- chef/provisioning/aws_driver

my yml is:

---
driver:
  name: ec2
  aws_ssh_key_id: key
  security_group_ids: ["sg-", "sg-"]
  reqion: us-east-1
  require_chef_omnibus: true
  subnet_id: subnet-x
  instance_type: t2.micro
  associate_public_ip: true
  interface: public

provisioner:
  name: chef_zero

platforms:
  - name: amazon-linux
    driver:
      image_id: ami-a4c7edb2
    transport:
      ssh_key: C:\Keys.pem
      connection_timeout: 10
      connection_retries: 5
      username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[steve-solr::default]
    attributes:

**Comment by cheeseplus** [comment]
It's been a bit since this was reported but this looks like chef-client not being able to load a gem this isn't anything specific with kitchen, let alone kitchen-ec2 so I'm closing the issue.

If you're still having issues, especially for an issue like this please join us on our mailing lists or Slack channel [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community).
