### ISSUE TITLE
Update to AWS-SDK v3

### ISSUE THREAD

**Issue by gcorpian** [test-kitchen/kitchen-ec2#443]
Kitchen-ec2 2.4.0 has a gem requirement of aws-sdk (~> 2) and when I updated to Ruby 2.6, I am getting deprecation warnings for aws-sdk-core/eager_loader.rb:22: warning: constant Struct::Tms is deprecated.  This is a cascading issue because I can't update aws-sdk to use the latest version which is 3.0.1.

**Comment by cheeseplus** [comment]
Kitchen-ec2 can't update the AWS SDK because of other dependencies in the chef ecosystem, namely inspec/kitchen-inspec and knife. Chef needs to update all three in conjunction or the ChefDK/Workstation will break.

Unfortunately there's not much that can be done until the above happens, otherwise we'd be making test-kitchen unusable in the ChefDK.

**Comment by jeffbyrnes** [comment]
I think this can be closed, since the aforementioned PRs effectively cover what needs be done from the position of this project.
