### ISSUE TITLE
Missing KITCHEN_PORT for ssh connexion

### ISSUE THREAD

**Issue by arthurlogilab** [test-kitchen/kitchen-ec2#468]
When using kitchen with vagrant/virtualbox, we have some test that get the SSH connexion environnment variables to connect via SSH to launch some tests (with the excellent testinfra https://testinfra.readthedocs.io/ ). Until using kitchen-ec2, we were relying on KITCHEN_PORT and KITCHEN_SSH_KEY etc.

While using kitchen-ec2, what variables should be used ?

**Comment by arthurlogilab** [comment]
I've just realised that I seem to be using version 2.2.2 

`/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-ec2-2.2.2/lib/kitchen/driver/ec2.rb`

Is this the problem ?

**Comment by marcparadise** [comment]
It looks like you might need to use AWS_SSH_KEY_ID instead of KITCHEN_SSH_KEY, assuming that the ssh key is available on ec2 for provisioning. 

@arthurlogilab given the time since this was open, and the number of versions of kitchen-ec2 that have released since then, I'm going to close the issue. If you find it's still occurring under current versions of kitchen-ec2, please re-open this.
